apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-controller
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-controller
subjects:
  - kind: ServiceAccount
    name: default
    namespace: helm-system
roleRef:
  kind: ClusterRole
  name: helm-controller
  apiGroup: rbac.authorization.k8s.io
