apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Update the version from https://github.com/cert-manager/cert-manager/releases
- https://github.com/cert-manager/cert-manager/releases/download/v1.10.0/cert-manager.yaml
- cloudflare-api-token-secret.yaml
- issuer.yaml
